server:
  port: ${SERVER_PORT:8080}
spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
      show-sql: true